name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_iOS:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild -scheme PermissionsSwiftUI -destination 'generic/platform=iOS' build
  test_iOS:
     runs-on: macos-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest-stable
     - name: Test
       run: xcodebuild -scheme PermissionsSwiftUI -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max' test
  Swiftformat:
    name: Check swiftformat
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose . --swiftversion 5.2
  SwiftDoc:
    name: Generate documentation
    runs-on: macos-latest
    steps:
      - name: Install Jazzy
        run: sudo gem install jazzy
      - name: Jazzy Doc
        run: jazzy --module PermissionsSwiftUI --swift-build-tool xcodebuild --build-tool-arguments -scheme,PermissionsSwiftUI,-sdk,iphoneos

